/**
 * Catálogo de marcas y modelos de impresoras de papel carta (Letter 8.5×11),
 * típicas en oficinas de Colombia, México y Estados Unidos.
 */

export interface ImpresoraMarcaCatalogItem {
  id: string;
  nombre: string;
  origen: string;
}

export interface ImpresoraModeloCatalogItem {
  id: string;
  marcaId: string;
  nombre: string;
  tipo: "laser" | "inkjet" | "mfp";
}

export const IMPRESORA_TIPO_LABEL: Record<
  ImpresoraModeloCatalogItem["tipo"],
  string
> = {
  laser: "Láser",
  inkjet: "Inyección",
  mfp: "Multifunción",
};

export const IMPRESORA_MARCAS_CATALOG: readonly ImpresoraMarcaCatalogItem[] = [
  { id: "hp", nombre: "HP", origen: "EE. UU." },
  { id: "brother", nombre: "Brother", origen: "Japón" },
  { id: "canon", nombre: "Canon", origen: "Japón" },
  { id: "epson", nombre: "Epson", origen: "Japón" },
  { id: "lexmark", nombre: "Lexmark", origen: "EE. UU." },
  { id: "xerox", nombre: "Xerox", origen: "EE. UU." },
  { id: "kyocera", nombre: "Kyocera", origen: "Japón" },
  { id: "ricoh", nombre: "Ricoh", origen: "Japón" },
  { id: "pantum", nombre: "Pantum", origen: "China" },
  { id: "oki", nombre: "OKI", origen: "Japón" },
  { id: "dell", nombre: "Dell", origen: "EE. UU." },
  { id: "samsung", nombre: "Samsung", origen: "Corea" },
];

/**
 * Modelos carta (Letter) habituales en oficinas CO / MX / US.
 * `marcaId` debe coincidir con `IMPRESORA_MARCAS_CATALOG[].id`.
 */
export const IMPRESORA_MODELOS_CATALOG: readonly ImpresoraModeloCatalogItem[] = [
  // ── HP LaserJet mono ──
  { id: "hp-lj-m15w", marcaId: "hp", nombre: "LaserJet Pro M15w", tipo: "laser" },
  { id: "hp-lj-m107w", marcaId: "hp", nombre: "LaserJet Pro M107w", tipo: "laser" },
  { id: "hp-lj-m203dw", marcaId: "hp", nombre: "LaserJet Pro M203dw", tipo: "laser" },
  { id: "hp-lj-m402dn", marcaId: "hp", nombre: "LaserJet Pro M402dn", tipo: "laser" },
  { id: "hp-lj-m402dw", marcaId: "hp", nombre: "LaserJet Pro M402dw", tipo: "laser" },
  { id: "hp-lj-m404dn", marcaId: "hp", nombre: "LaserJet Pro M404dn", tipo: "laser" },
  { id: "hp-lj-m404dw", marcaId: "hp", nombre: "LaserJet Pro M404dw", tipo: "laser" },
  { id: "hp-lj-m404n", marcaId: "hp", nombre: "LaserJet Pro M404n", tipo: "laser" },
  { id: "hp-lj-m405dn", marcaId: "hp", nombre: "LaserJet Pro M405dn", tipo: "laser" },
  { id: "hp-lj-m501dn", marcaId: "hp", nombre: "LaserJet Pro M501dn", tipo: "laser" },
  { id: "hp-lj-m506dn", marcaId: "hp", nombre: "LaserJet Enterprise M506dn", tipo: "laser" },
  { id: "hp-lj-m507dn", marcaId: "hp", nombre: "LaserJet Enterprise M507dn", tipo: "laser" },
  { id: "hp-lj-m608dn", marcaId: "hp", nombre: "LaserJet Enterprise M608dn", tipo: "laser" },
  { id: "hp-lj-m609dn", marcaId: "hp", nombre: "LaserJet Enterprise M609dn", tipo: "laser" },
  { id: "hp-lj-e40040dn", marcaId: "hp", nombre: "LaserJet Enterprise E40040dn", tipo: "laser" },
  { id: "hp-lj-e50145dn", marcaId: "hp", nombre: "LaserJet Enterprise E50145dn", tipo: "laser" },
  { id: "hp-lj-e60055dn", marcaId: "hp", nombre: "LaserJet Enterprise E60055dn", tipo: "laser" },
  { id: "hp-lj-e60155dn", marcaId: "hp", nombre: "LaserJet Enterprise E60155dn", tipo: "laser" },
  { id: "hp-lj-p1606dn", marcaId: "hp", nombre: "LaserJet P1606dn", tipo: "laser" },
  { id: "hp-lj-p2035n", marcaId: "hp", nombre: "LaserJet P2035n", tipo: "laser" },
  { id: "hp-lj-p2055dn", marcaId: "hp", nombre: "LaserJet P2055dn", tipo: "laser" },
  { id: "hp-lj-p3015dn", marcaId: "hp", nombre: "LaserJet P3015dn", tipo: "laser" },
  { id: "hp-lj-p4015n", marcaId: "hp", nombre: "LaserJet P4015n", tipo: "laser" },
  { id: "hp-lj-4200n", marcaId: "hp", nombre: "LaserJet 4200n", tipo: "laser" },
  // HP LaserJet MFP mono
  { id: "hp-mfp-m28w", marcaId: "hp", nombre: "LaserJet Pro MFP M28w", tipo: "mfp" },
  { id: "hp-mfp-m130nw", marcaId: "hp", nombre: "LaserJet Pro MFP M130nw", tipo: "mfp" },
  { id: "hp-mfp-m148dw", marcaId: "hp", nombre: "LaserJet Pro MFP M148dw", tipo: "mfp" },
  { id: "hp-mfp-m227fdw", marcaId: "hp", nombre: "LaserJet Pro MFP M227fdw", tipo: "mfp" },
  { id: "hp-mfp-m428fdn", marcaId: "hp", nombre: "LaserJet Pro MFP M428fdn", tipo: "mfp" },
  { id: "hp-mfp-m428fdw", marcaId: "hp", nombre: "LaserJet Pro MFP M428fdw", tipo: "mfp" },
  { id: "hp-mfp-m429fdw", marcaId: "hp", nombre: "LaserJet Pro MFP M429fdw", tipo: "mfp" },
  { id: "hp-mfp-m521dn", marcaId: "hp", nombre: "LaserJet Pro MFP M521dn", tipo: "mfp" },
  { id: "hp-mfp-m527dn", marcaId: "hp", nombre: "LaserJet Enterprise MFP M527dn", tipo: "mfp" },
  { id: "hp-mfp-m528dn", marcaId: "hp", nombre: "LaserJet Enterprise MFP M528dn", tipo: "mfp" },
  { id: "hp-mfp-e42540f", marcaId: "hp", nombre: "LaserJet Enterprise MFP E42540f", tipo: "mfp" },
  { id: "hp-mfp-e52645dn", marcaId: "hp", nombre: "LaserJet Enterprise MFP E52645dn", tipo: "mfp" },
  { id: "hp-mfp-e62655dn", marcaId: "hp", nombre: "LaserJet Enterprise MFP E62655dn", tipo: "mfp" },
  // HP Color LaserJet
  { id: "hp-clj-m154nw", marcaId: "hp", nombre: "Color LaserJet Pro M154nw", tipo: "laser" },
  { id: "hp-clj-m254dw", marcaId: "hp", nombre: "Color LaserJet Pro M254dw", tipo: "laser" },
  { id: "hp-clj-m255dw", marcaId: "hp", nombre: "Color LaserJet Pro M255dw", tipo: "laser" },
  { id: "hp-clj-m452dn", marcaId: "hp", nombre: "Color LaserJet Pro M452dn", tipo: "laser" },
  { id: "hp-clj-m452dw", marcaId: "hp", nombre: "Color LaserJet Pro M452dw", tipo: "laser" },
  { id: "hp-clj-m454dn", marcaId: "hp", nombre: "Color LaserJet Pro M454dn", tipo: "laser" },
  { id: "hp-clj-m454dw", marcaId: "hp", nombre: "Color LaserJet Pro M454dw", tipo: "laser" },
  { id: "hp-clj-m455dn", marcaId: "hp", nombre: "Color LaserJet Pro M455dn", tipo: "laser" },
  { id: "hp-clj-m552dn", marcaId: "hp", nombre: "Color LaserJet Enterprise M552dn", tipo: "laser" },
  { id: "hp-clj-m553dn", marcaId: "hp", nombre: "Color LaserJet Enterprise M553dn", tipo: "laser" },
  { id: "hp-clj-m554dn", marcaId: "hp", nombre: "Color LaserJet Enterprise M554dn", tipo: "laser" },
  { id: "hp-clj-m555dn", marcaId: "hp", nombre: "Color LaserJet Enterprise M555dn", tipo: "laser" },
  { id: "hp-clj-e45028dn", marcaId: "hp", nombre: "Color LaserJet Enterprise E45028dn", tipo: "laser" },
  { id: "hp-clj-e55040dn", marcaId: "hp", nombre: "Color LaserJet Enterprise E55040dn", tipo: "laser" },
  { id: "hp-clj-e65050dn", marcaId: "hp", nombre: "Color LaserJet Enterprise E65050dn", tipo: "laser" },
  // HP Color LaserJet MFP
  { id: "hp-cmfp-m180nw", marcaId: "hp", nombre: "Color LaserJet Pro MFP M180nw", tipo: "mfp" },
  { id: "hp-cmfp-m281fdw", marcaId: "hp", nombre: "Color LaserJet Pro MFP M281fdw", tipo: "mfp" },
  { id: "hp-cmfp-m283fdw", marcaId: "hp", nombre: "Color LaserJet Pro MFP M283fdw", tipo: "mfp" },
  { id: "hp-cmfp-m477fdw", marcaId: "hp", nombre: "Color LaserJet Pro MFP M477fdw", tipo: "mfp" },
  { id: "hp-cmfp-m479fdn", marcaId: "hp", nombre: "Color LaserJet Pro MFP M479fdn", tipo: "mfp" },
  { id: "hp-cmfp-m479fdw", marcaId: "hp", nombre: "Color LaserJet Pro MFP M479fdw", tipo: "mfp" },
  { id: "hp-cmfp-m480f", marcaId: "hp", nombre: "Color LaserJet Pro MFP M480f", tipo: "mfp" },
  { id: "hp-cmfp-m577dn", marcaId: "hp", nombre: "Color LaserJet Enterprise MFP M577dn", tipo: "mfp" },
  { id: "hp-cmfp-m578dn", marcaId: "hp", nombre: "Color LaserJet Enterprise MFP M578dn", tipo: "mfp" },
  { id: "hp-cmfp-e47528f", marcaId: "hp", nombre: "Color LaserJet Enterprise MFP E47528f", tipo: "mfp" },
  { id: "hp-cmfp-e57540c", marcaId: "hp", nombre: "Color LaserJet Enterprise MFP E57540c", tipo: "mfp" },
  // HP OfficeJet / DeskJet
  { id: "hp-oj-250", marcaId: "hp", nombre: "OfficeJet 250 Mobile", tipo: "inkjet" },
  { id: "hp-oj-3830", marcaId: "hp", nombre: "OfficeJet 3830", tipo: "mfp" },
  { id: "hp-oj-5255", marcaId: "hp", nombre: "OfficeJet 5255", tipo: "mfp" },
  { id: "hp-oj-6968", marcaId: "hp", nombre: "OfficeJet Pro 6968", tipo: "mfp" },
  { id: "hp-oj-6978", marcaId: "hp", nombre: "OfficeJet Pro 6978", tipo: "mfp" },
  { id: "hp-oj-7720", marcaId: "hp", nombre: "OfficeJet Pro 7720", tipo: "mfp" },
  { id: "hp-oj-7740", marcaId: "hp", nombre: "OfficeJet Pro 7740", tipo: "mfp" },
  { id: "hp-oj-8025e", marcaId: "hp", nombre: "OfficeJet Pro 8025e", tipo: "mfp" },
  { id: "hp-oj-9010e", marcaId: "hp", nombre: "OfficeJet Pro 9010e", tipo: "mfp" },
  { id: "hp-oj-9015e", marcaId: "hp", nombre: "OfficeJet Pro 9015e", tipo: "inkjet" },
  { id: "hp-oj-9020e", marcaId: "hp", nombre: "OfficeJet Pro 9020e", tipo: "mfp" },
  { id: "hp-oj-9025e", marcaId: "hp", nombre: "OfficeJet Pro 9025e", tipo: "mfp" },
  { id: "hp-oj-9730e", marcaId: "hp", nombre: "OfficeJet Pro 9730e", tipo: "mfp" },
  { id: "hp-dj-2755e", marcaId: "hp", nombre: "DeskJet 2755e", tipo: "inkjet" },
  { id: "hp-dj-4155e", marcaId: "hp", nombre: "DeskJet 4155e", tipo: "mfp" },
  { id: "hp-envy-6055e", marcaId: "hp", nombre: "ENVY 6055e", tipo: "mfp" },
  { id: "hp-envy-6455e", marcaId: "hp", nombre: "ENVY 6455e", tipo: "mfp" },
  { id: "hp-smart-tank-5101", marcaId: "hp", nombre: "Smart Tank 5101", tipo: "inkjet" },
  { id: "hp-smart-tank-580", marcaId: "hp", nombre: "Smart Tank 580", tipo: "mfp" },
  { id: "hp-smart-tank-7602", marcaId: "hp", nombre: "Smart Tank 7602", tipo: "mfp" },

  // ── Brother HL (láser mono) ──
  { id: "br-hl-l2300d", marcaId: "brother", nombre: "HL-L2300D", tipo: "laser" },
  { id: "br-hl-l2320d", marcaId: "brother", nombre: "HL-L2320D", tipo: "laser" },
  { id: "br-hl-l2350dw", marcaId: "brother", nombre: "HL-L2350DW", tipo: "laser" },
  { id: "br-hl-l2370dw", marcaId: "brother", nombre: "HL-L2370DW", tipo: "laser" },
  { id: "br-hl-l2390dw", marcaId: "brother", nombre: "HL-L2390DW", tipo: "laser" },
  { id: "br-hl-l2395dw", marcaId: "brother", nombre: "HL-L2395DW", tipo: "laser" },
  { id: "br-hl-l2400dw", marcaId: "brother", nombre: "HL-L2400DW", tipo: "laser" },
  { id: "br-hl-l2460dw", marcaId: "brother", nombre: "HL-L2460DW", tipo: "laser" },
  { id: "br-hl-l5000d", marcaId: "brother", nombre: "HL-L5000D", tipo: "laser" },
  { id: "br-hl-l5100dn", marcaId: "brother", nombre: "HL-L5100DN", tipo: "laser" },
  { id: "br-hl-l5200dw", marcaId: "brother", nombre: "HL-L5200DW", tipo: "laser" },
  { id: "br-hl-l6200dw", marcaId: "brother", nombre: "HL-L6200DW", tipo: "laser" },
  { id: "br-hl-l6400dw", marcaId: "brother", nombre: "HL-L6400DW", tipo: "laser" },
  { id: "br-hl-l6400dwg", marcaId: "brother", nombre: "HL-L6400DWG", tipo: "laser" },
  { id: "br-hl-l6415dw", marcaId: "brother", nombre: "HL-L6415DW", tipo: "laser" },
  { id: "br-hl-l8260cdw", marcaId: "brother", nombre: "HL-L8260CDW", tipo: "laser" },
  { id: "br-hl-l8360cdw", marcaId: "brother", nombre: "HL-L8360CDW", tipo: "laser" },
  { id: "br-hl-l9310cdw", marcaId: "brother", nombre: "HL-L9310CDW", tipo: "laser" },
  { id: "br-hl-l9470cdn", marcaId: "brother", nombre: "HL-L9470CDN", tipo: "laser" },
  // Brother MFC / DCP
  { id: "br-dcp-l2550dw", marcaId: "brother", nombre: "DCP-L2550DW", tipo: "mfp" },
  { id: "br-dcp-l2640dw", marcaId: "brother", nombre: "DCP-L2640DW", tipo: "mfp" },
  { id: "br-mfc-l2710dw", marcaId: "brother", nombre: "MFC-L2710DW", tipo: "mfp" },
  { id: "br-mfc-l2750dw", marcaId: "brother", nombre: "MFC-L2750DW", tipo: "mfp" },
  { id: "br-mfc-l2820dw", marcaId: "brother", nombre: "MFC-L2820DW", tipo: "mfp" },
  { id: "br-mfc-l2900dw", marcaId: "brother", nombre: "MFC-L2900DW", tipo: "mfp" },
  { id: "br-mfc-l3710cw", marcaId: "brother", nombre: "MFC-L3710CW", tipo: "mfp" },
  { id: "br-mfc-l3750cdw", marcaId: "brother", nombre: "MFC-L3750CDW", tipo: "mfp" },
  { id: "br-mfc-l3770cdw", marcaId: "brother", nombre: "MFC-L3770CDW", tipo: "mfp" },
  { id: "br-mfc-l5700dw", marcaId: "brother", nombre: "MFC-L5700DW", tipo: "mfp" },
  { id: "br-mfc-l5800dw", marcaId: "brother", nombre: "MFC-L5800DW", tipo: "mfp" },
  { id: "br-mfc-l5900dw", marcaId: "brother", nombre: "MFC-L5900DW", tipo: "mfp" },
  { id: "br-mfc-l6700dw", marcaId: "brother", nombre: "MFC-L6700DW", tipo: "mfp" },
  { id: "br-mfc-l6900dw", marcaId: "brother", nombre: "MFC-L6900DW", tipo: "mfp" },
  { id: "br-mfc-l8610cdw", marcaId: "brother", nombre: "MFC-L8610CDW", tipo: "mfp" },
  { id: "br-mfc-l8690cdw", marcaId: "brother", nombre: "MFC-L8690CDW", tipo: "mfp" },
  { id: "br-mfc-l8900cdw", marcaId: "brother", nombre: "MFC-L8900CDW", tipo: "mfp" },
  { id: "br-mfc-l9570cdw", marcaId: "brother", nombre: "MFC-L9570CDW", tipo: "mfp" },
  { id: "br-mfc-l9610cdn", marcaId: "brother", nombre: "MFC-L9610CDN", tipo: "mfp" },
  // Brother inkjet
  { id: "br-mfc-j4335dw", marcaId: "brother", nombre: "MFC-J4335DW", tipo: "inkjet" },
  { id: "br-mfc-j4535dw", marcaId: "brother", nombre: "MFC-J4535DW", tipo: "mfp" },
  { id: "br-mfc-j5330dw", marcaId: "brother", nombre: "MFC-J5330DW", tipo: "mfp" },
  { id: "br-mfc-j5845dw", marcaId: "brother", nombre: "MFC-J5845DW", tipo: "mfp" },
  { id: "br-mfc-j5945dw", marcaId: "brother", nombre: "MFC-J5945DW", tipo: "mfp" },
  { id: "br-mfc-j6540dw", marcaId: "brother", nombre: "MFC-J6540DW", tipo: "mfp" },
  { id: "br-mfc-j6945dw", marcaId: "brother", nombre: "MFC-J6945DW", tipo: "mfp" },
  { id: "br-mfc-j6955dw", marcaId: "brother", nombre: "MFC-J6955DW", tipo: "inkjet" },
  { id: "br-mfc-j775dw", marcaId: "brother", nombre: "MFC-J775DW", tipo: "mfp" },
  { id: "br-mfc-j985dw", marcaId: "brother", nombre: "MFC-J985DW", tipo: "mfp" },

  // ── Canon imageCLASS ──
  { id: "cn-lbp122dw", marcaId: "canon", nombre: "imageCLASS LBP122dw", tipo: "laser" },
  { id: "cn-lbp162dw", marcaId: "canon", nombre: "imageCLASS LBP162dw", tipo: "laser" },
  { id: "cn-lbp214dw", marcaId: "canon", nombre: "imageCLASS LBP214dw", tipo: "laser" },
  { id: "cn-lbp215dw", marcaId: "canon", nombre: "imageCLASS LBP215dw", tipo: "laser" },
  { id: "cn-lbp226dw", marcaId: "canon", nombre: "imageCLASS LBP226dw", tipo: "laser" },
  { id: "cn-lbp227dw", marcaId: "canon", nombre: "imageCLASS LBP227dw", tipo: "laser" },
  { id: "cn-lbp228dw", marcaId: "canon", nombre: "imageCLASS LBP228dw", tipo: "laser" },
  { id: "cn-lbp251dw", marcaId: "canon", nombre: "imageCLASS LBP251dw", tipo: "laser" },
  { id: "cn-lbp312dn", marcaId: "canon", nombre: "imageCLASS LBP312dn", tipo: "laser" },
  { id: "cn-lbp351dn", marcaId: "canon", nombre: "imageCLASS LBP351dn", tipo: "laser" },
  { id: "cn-lbp654cdw", marcaId: "canon", nombre: "imageCLASS LBP654Cdw", tipo: "laser" },
  { id: "cn-lbp664cdw", marcaId: "canon", nombre: "imageCLASS LBP664Cdw", tipo: "laser" },
  { id: "cn-mf264dw", marcaId: "canon", nombre: "imageCLASS MF264dw", tipo: "mfp" },
  { id: "cn-mf269dw", marcaId: "canon", nombre: "imageCLASS MF269dw", tipo: "mfp" },
  { id: "cn-mf445dw", marcaId: "canon", nombre: "imageCLASS MF445dw", tipo: "mfp" },
  { id: "cn-mf449dw", marcaId: "canon", nombre: "imageCLASS MF449dw", tipo: "mfp" },
  { id: "cn-mf455dw", marcaId: "canon", nombre: "imageCLASS MF455dw", tipo: "mfp" },
  { id: "cn-mf465dw", marcaId: "canon", nombre: "imageCLASS MF465dw", tipo: "mfp" },
  { id: "cn-mf644cdw", marcaId: "canon", nombre: "imageCLASS MF644Cdw", tipo: "mfp" },
  { id: "cn-mf656cdw", marcaId: "canon", nombre: "imageCLASS MF656Cdw", tipo: "mfp" },
  { id: "cn-mf731cdw", marcaId: "canon", nombre: "imageCLASS MF731Cdw", tipo: "mfp" },
  { id: "cn-mf743cdw", marcaId: "canon", nombre: "imageCLASS MF743Cdw", tipo: "mfp" },
  { id: "cn-mf746cdw", marcaId: "canon", nombre: "imageCLASS MF746Cdw", tipo: "mfp" },
  { id: "cn-mf753cdw", marcaId: "canon", nombre: "imageCLASS MF753Cdw", tipo: "mfp" },
  // Canon MAXIFY / PIXMA / imageRUNNER
  { id: "cn-gx2020", marcaId: "canon", nombre: "MAXIFY GX2020", tipo: "inkjet" },
  { id: "cn-gx4020", marcaId: "canon", nombre: "MAXIFY GX4020", tipo: "inkjet" },
  { id: "cn-gx5020", marcaId: "canon", nombre: "MAXIFY GX5020", tipo: "inkjet" },
  { id: "cn-gx6020", marcaId: "canon", nombre: "MAXIFY GX6020", tipo: "inkjet" },
  { id: "cn-gx7020", marcaId: "canon", nombre: "MAXIFY GX7020", tipo: "mfp" },
  { id: "cn-mb2720", marcaId: "canon", nombre: "MAXIFY MB2720", tipo: "mfp" },
  { id: "cn-mb5120", marcaId: "canon", nombre: "MAXIFY MB5120", tipo: "mfp" },
  { id: "cn-mb5420", marcaId: "canon", nombre: "MAXIFY MB5420", tipo: "mfp" },
  { id: "cn-pixma-g7020", marcaId: "canon", nombre: "PIXMA G7020", tipo: "mfp" },
  { id: "cn-pixma-tr8620a", marcaId: "canon", nombre: "PIXMA TR8620a", tipo: "mfp" },
  { id: "cn-pixma-ts8320", marcaId: "canon", nombre: "PIXMA TS8320", tipo: "mfp" },
  { id: "cn-ira-c3520i", marcaId: "canon", nombre: "imageRUNNER ADVANCE C3520i", tipo: "mfp" },
  { id: "cn-ira-c3530i", marcaId: "canon", nombre: "imageRUNNER ADVANCE C3530i", tipo: "mfp" },
  { id: "cn-ira-c356i", marcaId: "canon", nombre: "imageRUNNER ADVANCE C356i", tipo: "mfp" },
  { id: "cn-ira-c5535i", marcaId: "canon", nombre: "imageRUNNER ADVANCE C5535i", tipo: "mfp" },
  { id: "cn-ira-c5550i", marcaId: "canon", nombre: "imageRUNNER ADVANCE C5550i", tipo: "mfp" },
  { id: "cn-ira-dx-c3720i", marcaId: "canon", nombre: "imageRUNNER ADVANCE DX C3720i", tipo: "mfp" },
  { id: "cn-ira-dx-c477i", marcaId: "canon", nombre: "imageRUNNER ADVANCE DX C477i", tipo: "mfp" },
  { id: "cn-ira-1643i", marcaId: "canon", nombre: "imageRUNNER 1643i", tipo: "mfp" },
  { id: "cn-ira-2425i", marcaId: "canon", nombre: "imageRUNNER 2425i", tipo: "mfp" },

  // ── Epson EcoTank / WorkForce ──
  { id: "ep-et-2800", marcaId: "epson", nombre: "EcoTank ET-2800", tipo: "inkjet" },
  { id: "ep-et-2803", marcaId: "epson", nombre: "EcoTank ET-2803", tipo: "inkjet" },
  { id: "ep-et-2850", marcaId: "epson", nombre: "EcoTank ET-2850", tipo: "inkjet" },
  { id: "ep-et-3850", marcaId: "epson", nombre: "EcoTank ET-3850", tipo: "mfp" },
  { id: "ep-et-4800", marcaId: "epson", nombre: "EcoTank ET-4800", tipo: "mfp" },
  { id: "ep-et-4850", marcaId: "epson", nombre: "EcoTank ET-4850", tipo: "mfp" },
  { id: "ep-et-5150", marcaId: "epson", nombre: "EcoTank ET-5150", tipo: "mfp" },
  { id: "ep-et-5170", marcaId: "epson", nombre: "EcoTank Pro ET-5170", tipo: "mfp" },
  { id: "ep-et-5800", marcaId: "epson", nombre: "EcoTank Pro ET-5800", tipo: "mfp" },
  { id: "ep-et-5850", marcaId: "epson", nombre: "EcoTank Pro ET-5850", tipo: "mfp" },
  { id: "ep-et-16650", marcaId: "epson", nombre: "EcoTank ET-16650", tipo: "mfp" },
  { id: "ep-et-m1170", marcaId: "epson", nombre: "EcoTank ET-M1170", tipo: "laser" },
  { id: "ep-et-m1660", marcaId: "epson", nombre: "EcoTank ET-M1660", tipo: "mfp" },
  { id: "ep-et-m3170", marcaId: "epson", nombre: "EcoTank ET-M3170", tipo: "mfp" },
  { id: "ep-wf-2830", marcaId: "epson", nombre: "WorkForce WF-2830", tipo: "mfp" },
  { id: "ep-wf-2850", marcaId: "epson", nombre: "WorkForce WF-2850", tipo: "mfp" },
  { id: "ep-wf-2860", marcaId: "epson", nombre: "WorkForce WF-2860", tipo: "mfp" },
  { id: "ep-wf-2950", marcaId: "epson", nombre: "WorkForce WF-2950", tipo: "mfp" },
  { id: "ep-wf-3720", marcaId: "epson", nombre: "WorkForce Pro WF-3720", tipo: "mfp" },
  { id: "ep-wf-4740", marcaId: "epson", nombre: "WorkForce Pro WF-4740", tipo: "mfp" },
  { id: "ep-wf-4830", marcaId: "epson", nombre: "WorkForce Pro WF-4830", tipo: "mfp" },
  { id: "ep-wf-4820", marcaId: "epson", nombre: "WorkForce Pro WF-4820", tipo: "mfp" },
  { id: "ep-wf-c5290", marcaId: "epson", nombre: "WorkForce Pro WF-C5290", tipo: "inkjet" },
  { id: "ep-wf-c5790", marcaId: "epson", nombre: "WorkForce Pro WF-C5790", tipo: "mfp" },
  { id: "ep-wf-c5890", marcaId: "epson", nombre: "WorkForce Pro WF-C5890", tipo: "mfp" },
  { id: "ep-wf-c8690", marcaId: "epson", nombre: "WorkForce Pro WF-C8690", tipo: "mfp" },
  { id: "ep-wf-m5299", marcaId: "epson", nombre: "WorkForce Pro WF-M5299", tipo: "inkjet" },
  { id: "ep-wf-m5799", marcaId: "epson", nombre: "WorkForce Pro WF-M5799", tipo: "mfp" },
  { id: "ep-xp-4100", marcaId: "epson", nombre: "Expression Home XP-4100", tipo: "mfp" },
  { id: "ep-xp-5100", marcaId: "epson", nombre: "Expression Premium XP-5100", tipo: "mfp" },
  { id: "ep-l3250", marcaId: "epson", nombre: "L3250 EcoTank", tipo: "inkjet" },
  { id: "ep-l4260", marcaId: "epson", nombre: "L4260 EcoTank", tipo: "mfp" },
  { id: "ep-l6270", marcaId: "epson", nombre: "L6270 EcoTank", tipo: "mfp" },
  { id: "ep-l6490", marcaId: "epson", nombre: "L6490 EcoTank", tipo: "mfp" },

  // ── Lexmark ──
  { id: "lx-b2236dw", marcaId: "lexmark", nombre: "B2236dw", tipo: "laser" },
  { id: "lx-b2338dw", marcaId: "lexmark", nombre: "B2338dw", tipo: "laser" },
  { id: "lx-b2442dw", marcaId: "lexmark", nombre: "B2442dw", tipo: "laser" },
  { id: "lx-b2546dw", marcaId: "lexmark", nombre: "B2546dw", tipo: "laser" },
  { id: "lx-b2650dn", marcaId: "lexmark", nombre: "B2650dn", tipo: "laser" },
  { id: "lx-b2865dw", marcaId: "lexmark", nombre: "B2865dw", tipo: "laser" },
  { id: "lx-ms331dn", marcaId: "lexmark", nombre: "MS331dn", tipo: "laser" },
  { id: "lx-ms421dn", marcaId: "lexmark", nombre: "MS421dn", tipo: "laser" },
  { id: "lx-ms431dn", marcaId: "lexmark", nombre: "MS431dn", tipo: "laser" },
  { id: "lx-ms521dn", marcaId: "lexmark", nombre: "MS521dn", tipo: "laser" },
  { id: "lx-ms621dn", marcaId: "lexmark", nombre: "MS621dn", tipo: "laser" },
  { id: "lx-ms821dn", marcaId: "lexmark", nombre: "MS821dn", tipo: "laser" },
  { id: "lx-ms823dn", marcaId: "lexmark", nombre: "MS823dn", tipo: "laser" },
  { id: "lx-cs331dw", marcaId: "lexmark", nombre: "CS331dw", tipo: "laser" },
  { id: "lx-cs421dn", marcaId: "lexmark", nombre: "CS421dn", tipo: "laser" },
  { id: "lx-cs431dw", marcaId: "lexmark", nombre: "CS431dw", tipo: "laser" },
  { id: "lx-cs521dn", marcaId: "lexmark", nombre: "CS521dn", tipo: "laser" },
  { id: "lx-cs820de", marcaId: "lexmark", nombre: "CS820de", tipo: "laser" },
  { id: "lx-c3224dw", marcaId: "lexmark", nombre: "C3224dw", tipo: "laser" },
  { id: "lx-c3326dw", marcaId: "lexmark", nombre: "C3326dw", tipo: "laser" },
  { id: "lx-c3426dw", marcaId: "lexmark", nombre: "C3426dw", tipo: "laser" },
  { id: "lx-mb2236adw", marcaId: "lexmark", nombre: "MB2236adw", tipo: "mfp" },
  { id: "lx-mb2442adwe", marcaId: "lexmark", nombre: "MB2442adwe", tipo: "mfp" },
  { id: "lx-mb2546adw", marcaId: "lexmark", nombre: "MB2546adw", tipo: "mfp" },
  { id: "lx-mx331adn", marcaId: "lexmark", nombre: "MX331adn", tipo: "mfp" },
  { id: "lx-mx421ade", marcaId: "lexmark", nombre: "MX421ade", tipo: "mfp" },
  { id: "lx-mx431adn", marcaId: "lexmark", nombre: "MX431adn", tipo: "mfp" },
  { id: "lx-mx521ade", marcaId: "lexmark", nombre: "MX521ade", tipo: "mfp" },
  { id: "lx-mx622ade", marcaId: "lexmark", nombre: "MX622ade", tipo: "mfp" },
  { id: "lx-mx721ade", marcaId: "lexmark", nombre: "MX721ade", tipo: "mfp" },
  { id: "lx-mx822ade", marcaId: "lexmark", nombre: "MX822ade", tipo: "mfp" },
  { id: "lx-mc3224dwe", marcaId: "lexmark", nombre: "MC3224dwe", tipo: "mfp" },
  { id: "lx-mc3326adwe", marcaId: "lexmark", nombre: "MC3326adwe", tipo: "mfp" },
  { id: "lx-mc3426adw", marcaId: "lexmark", nombre: "MC3426adw", tipo: "mfp" },
  { id: "lx-cx331adwe", marcaId: "lexmark", nombre: "CX331adwe", tipo: "mfp" },
  { id: "lx-cx421adn", marcaId: "lexmark", nombre: "CX421adn", tipo: "mfp" },
  { id: "lx-cx431adw", marcaId: "lexmark", nombre: "CX431adw", tipo: "mfp" },
  { id: "lx-cx522ade", marcaId: "lexmark", nombre: "CX522ade", tipo: "mfp" },
  { id: "lx-cx725de", marcaId: "lexmark", nombre: "CX725de", tipo: "mfp" },
  { id: "lx-cx825de", marcaId: "lexmark", nombre: "CX825de", tipo: "mfp" },

  // ── Xerox ──
  { id: "xr-b210", marcaId: "xerox", nombre: "B210", tipo: "laser" },
  { id: "xr-b215", marcaId: "xerox", nombre: "B215", tipo: "mfp" },
  { id: "xr-b225", marcaId: "xerox", nombre: "B225", tipo: "mfp" },
  { id: "xr-b230", marcaId: "xerox", nombre: "B230", tipo: "laser" },
  { id: "xr-b235", marcaId: "xerox", nombre: "B235", tipo: "mfp" },
  { id: "xr-b310", marcaId: "xerox", nombre: "B310", tipo: "laser" },
  { id: "xr-b315", marcaId: "xerox", nombre: "B315", tipo: "mfp" },
  { id: "xr-b410", marcaId: "xerox", nombre: "B410", tipo: "laser" },
  { id: "xr-b415", marcaId: "xerox", nombre: "B415", tipo: "mfp" },
  { id: "xr-b610", marcaId: "xerox", nombre: "VersaLink B610", tipo: "laser" },
  { id: "xr-b615", marcaId: "xerox", nombre: "VersaLink B615", tipo: "mfp" },
  { id: "xr-b405", marcaId: "xerox", nombre: "VersaLink B405", tipo: "mfp" },
  { id: "xr-b605", marcaId: "xerox", nombre: "VersaLink B605", tipo: "mfp" },
  { id: "xr-b7025", marcaId: "xerox", nombre: "VersaLink B7025", tipo: "mfp" },
  { id: "xr-b7030", marcaId: "xerox", nombre: "VersaLink B7030", tipo: "mfp" },
  { id: "xr-c230", marcaId: "xerox", nombre: "C230", tipo: "laser" },
  { id: "xr-c235", marcaId: "xerox", nombre: "C235", tipo: "mfp" },
  { id: "xr-c310", marcaId: "xerox", nombre: "C310", tipo: "laser" },
  { id: "xr-c315", marcaId: "xerox", nombre: "C315", tipo: "mfp" },
  { id: "xr-c400", marcaId: "xerox", nombre: "VersaLink C400", tipo: "laser" },
  { id: "xr-c405", marcaId: "xerox", nombre: "VersaLink C405", tipo: "mfp" },
  { id: "xr-c500", marcaId: "xerox", nombre: "VersaLink C500", tipo: "laser" },
  { id: "xr-c505", marcaId: "xerox", nombre: "VersaLink C505", tipo: "mfp" },
  { id: "xr-c600", marcaId: "xerox", nombre: "VersaLink C600", tipo: "laser" },
  { id: "xr-c605", marcaId: "xerox", nombre: "VersaLink C605", tipo: "mfp" },
  { id: "xr-c7000", marcaId: "xerox", nombre: "VersaLink C7000", tipo: "laser" },
  { id: "xr-c7020", marcaId: "xerox", nombre: "VersaLink C7020", tipo: "mfp" },
  { id: "xr-c7025", marcaId: "xerox", nombre: "VersaLink C7025", tipo: "mfp" },
  { id: "xr-alta-b8045", marcaId: "xerox", nombre: "AltaLink B8045", tipo: "mfp" },
  { id: "xr-alta-b8055", marcaId: "xerox", nombre: "AltaLink B8055", tipo: "mfp" },
  { id: "xr-alta-c8030", marcaId: "xerox", nombre: "AltaLink C8030", tipo: "mfp" },
  { id: "xr-alta-c8035", marcaId: "xerox", nombre: "AltaLink C8035", tipo: "mfp" },
  { id: "xr-alta-c8045", marcaId: "xerox", nombre: "AltaLink C8045", tipo: "mfp" },
  { id: "xr-wc-6515", marcaId: "xerox", nombre: "WorkCentre 6515", tipo: "mfp" },
  { id: "xr-wc-6655", marcaId: "xerox", nombre: "WorkCentre 6655", tipo: "mfp" },
  { id: "xr-phaser-6510", marcaId: "xerox", nombre: "Phaser 6510", tipo: "laser" },
  { id: "xr-phaser-3330", marcaId: "xerox", nombre: "Phaser 3330", tipo: "laser" },

  // ── Kyocera ECOSYS ──
  { id: "ky-p2040dn", marcaId: "kyocera", nombre: "ECOSYS P2040dn", tipo: "laser" },
  { id: "ky-p2040dw", marcaId: "kyocera", nombre: "ECOSYS P2040dw", tipo: "laser" },
  { id: "ky-p2235dn", marcaId: "kyocera", nombre: "ECOSYS P2235dn", tipo: "laser" },
  { id: "ky-p2235dw", marcaId: "kyocera", nombre: "ECOSYS P2235dw", tipo: "laser" },
  { id: "ky-p3045dn", marcaId: "kyocera", nombre: "ECOSYS P3045dn", tipo: "laser" },
  { id: "ky-p3145dn", marcaId: "kyocera", nombre: "ECOSYS P3145dn", tipo: "laser" },
  { id: "ky-p3150dn", marcaId: "kyocera", nombre: "ECOSYS P3150dn", tipo: "laser" },
  { id: "ky-p3155dn", marcaId: "kyocera", nombre: "ECOSYS P3155dn", tipo: "laser" },
  { id: "ky-p4060dn", marcaId: "kyocera", nombre: "ECOSYS P4060dn", tipo: "laser" },
  { id: "ky-p5021cdn", marcaId: "kyocera", nombre: "ECOSYS P5021cdn", tipo: "laser" },
  { id: "ky-p5021cdw", marcaId: "kyocera", nombre: "ECOSYS P5021cdw", tipo: "laser" },
  { id: "ky-p5026cdn", marcaId: "kyocera", nombre: "ECOSYS P5026cdn", tipo: "laser" },
  { id: "ky-p5026cdw", marcaId: "kyocera", nombre: "ECOSYS P5026cdw", tipo: "laser" },
  { id: "ky-p6230cdn", marcaId: "kyocera", nombre: "ECOSYS P6230cdn", tipo: "laser" },
  { id: "ky-p6235cdn", marcaId: "kyocera", nombre: "ECOSYS P6235cdn", tipo: "laser" },
  { id: "ky-m2040dn", marcaId: "kyocera", nombre: "ECOSYS M2040dn", tipo: "mfp" },
  { id: "ky-m2135dn", marcaId: "kyocera", nombre: "ECOSYS M2135dn", tipo: "mfp" },
  { id: "ky-m2540dw", marcaId: "kyocera", nombre: "ECOSYS M2540dw", tipo: "mfp" },
  { id: "ky-m2635dw", marcaId: "kyocera", nombre: "ECOSYS M2635dw", tipo: "mfp" },
  { id: "ky-m2640idw", marcaId: "kyocera", nombre: "ECOSYS M2640idw", tipo: "mfp" },
  { id: "ky-m3145dn", marcaId: "kyocera", nombre: "ECOSYS M3145dn", tipo: "mfp" },
  { id: "ky-m3655idn", marcaId: "kyocera", nombre: "ECOSYS M3655idn", tipo: "mfp" },
  { id: "ky-m3660idn", marcaId: "kyocera", nombre: "ECOSYS M3660idn", tipo: "mfp" },
  { id: "ky-m3860idn", marcaId: "kyocera", nombre: "ECOSYS M3860idn", tipo: "mfp" },
  { id: "ky-m5521cdn", marcaId: "kyocera", nombre: "ECOSYS M5521cdn", tipo: "mfp" },
  { id: "ky-m5521cdw", marcaId: "kyocera", nombre: "ECOSYS M5521cdw", tipo: "mfp" },
  { id: "ky-m5526cdn", marcaId: "kyocera", nombre: "ECOSYS M5526cdn", tipo: "mfp" },
  { id: "ky-m5526cdw", marcaId: "kyocera", nombre: "ECOSYS M5526cdw", tipo: "mfp" },
  { id: "ky-m6230cidn", marcaId: "kyocera", nombre: "ECOSYS M6230cidn", tipo: "mfp" },
  { id: "ky-m6630cidn", marcaId: "kyocera", nombre: "ECOSYS M6630cidn", tipo: "mfp" },
  { id: "ky-ta-2554ci", marcaId: "kyocera", nombre: "TASKalfa 2554ci", tipo: "mfp" },
  { id: "ky-ta-3554ci", marcaId: "kyocera", nombre: "TASKalfa 3554ci", tipo: "mfp" },
  { id: "ky-ta-4054ci", marcaId: "kyocera", nombre: "TASKalfa 4054ci", tipo: "mfp" },
  { id: "ky-ta-5054ci", marcaId: "kyocera", nombre: "TASKalfa 5054ci", tipo: "mfp" },
  { id: "ky-ta-2553ci", marcaId: "kyocera", nombre: "TASKalfa 2553ci", tipo: "mfp" },
  { id: "ky-ta-3253ci", marcaId: "kyocera", nombre: "TASKalfa 3253ci", tipo: "mfp" },

  // ── Ricoh ──
  { id: "ri-sp330dn", marcaId: "ricoh", nombre: "SP 330DN", tipo: "laser" },
  { id: "ri-sp3710dn", marcaId: "ricoh", nombre: "SP 3710DN", tipo: "laser" },
  { id: "ri-sp4510dn", marcaId: "ricoh", nombre: "SP 4510DN", tipo: "laser" },
  { id: "ri-sp5300dn", marcaId: "ricoh", nombre: "SP 5300DN", tipo: "laser" },
  { id: "ri-spc260sfnw", marcaId: "ricoh", nombre: "SP C260SFNw", tipo: "mfp" },
  { id: "ri-spc261sfnw", marcaId: "ricoh", nombre: "SP C261SFNw", tipo: "mfp" },
  { id: "ri-spc360sfnw", marcaId: "ricoh", nombre: "SP C360SFNw", tipo: "mfp" },
  { id: "ri-spc840dn", marcaId: "ricoh", nombre: "SP C840DN", tipo: "laser" },
  { id: "ri-p-501", marcaId: "ricoh", nombre: "P 501", tipo: "laser" },
  { id: "ri-p-502", marcaId: "ricoh", nombre: "P 502", tipo: "laser" },
  { id: "ri-p-c600", marcaId: "ricoh", nombre: "P C600", tipo: "laser" },
  { id: "ri-im350", marcaId: "ricoh", nombre: "IM 350", tipo: "mfp" },
  { id: "ri-im350f", marcaId: "ricoh", nombre: "IM 350F", tipo: "mfp" },
  { id: "ri-im430f", marcaId: "ricoh", nombre: "IM 430F", tipo: "mfp" },
  { id: "ri-im550f", marcaId: "ricoh", nombre: "IM 550F", tipo: "mfp" },
  { id: "ri-im600f", marcaId: "ricoh", nombre: "IM 600F", tipo: "mfp" },
  { id: "ri-imc2000", marcaId: "ricoh", nombre: "IM C2000", tipo: "mfp" },
  { id: "ri-imc2500", marcaId: "ricoh", nombre: "IM C2500", tipo: "mfp" },
  { id: "ri-imc3000", marcaId: "ricoh", nombre: "IM C3000", tipo: "mfp" },
  { id: "ri-imc3500", marcaId: "ricoh", nombre: "IM C3500", tipo: "mfp" },
  { id: "ri-imc4500", marcaId: "ricoh", nombre: "IM C4500", tipo: "mfp" },
  { id: "ri-imc5500", marcaId: "ricoh", nombre: "IM C5500", tipo: "mfp" },
  { id: "ri-imc6000", marcaId: "ricoh", nombre: "IM C6000", tipo: "mfp" },
  { id: "ri-mp-c3004ex", marcaId: "ricoh", nombre: "MP C3004ex", tipo: "mfp" },
  { id: "ri-mp-c3504ex", marcaId: "ricoh", nombre: "MP C3504ex", tipo: "mfp" },
  { id: "ri-mp-c4504ex", marcaId: "ricoh", nombre: "MP C4504ex", tipo: "mfp" },
  { id: "ri-mp-4055", marcaId: "ricoh", nombre: "MP 4055", tipo: "mfp" },
  { id: "ri-mp-5055", marcaId: "ricoh", nombre: "MP 5055", tipo: "mfp" },
  { id: "ri-mp-6055", marcaId: "ricoh", nombre: "MP 6055", tipo: "mfp" },

  // ── Pantum (LatAm) ──
  { id: "pa-p2500w", marcaId: "pantum", nombre: "P2500W", tipo: "laser" },
  { id: "pa-p2509", marcaId: "pantum", nombre: "P2509", tipo: "laser" },
  { id: "pa-p2509w", marcaId: "pantum", nombre: "P2509W", tipo: "laser" },
  { id: "pa-p3010dw", marcaId: "pantum", nombre: "P3010DW", tipo: "laser" },
  { id: "pa-p3300dw", marcaId: "pantum", nombre: "P3300DW", tipo: "laser" },
  { id: "pa-p3305dw", marcaId: "pantum", nombre: "P3305DW", tipo: "laser" },
  { id: "pa-p3500dn", marcaId: "pantum", nombre: "P3500DN", tipo: "laser" },
  { id: "pa-bp5100dn", marcaId: "pantum", nombre: "BP5100DN", tipo: "laser" },
  { id: "pa-bm5100adn", marcaId: "pantum", nombre: "BM5100ADN", tipo: "mfp" },
  { id: "pa-m6500w", marcaId: "pantum", nombre: "M6500W", tipo: "mfp" },
  { id: "pa-m6509w", marcaId: "pantum", nombre: "M6509W", tipo: "mfp" },
  { id: "pa-m6550nw", marcaId: "pantum", nombre: "M6550NW", tipo: "mfp" },
  { id: "pa-m6600nw", marcaId: "pantum", nombre: "M6600NW", tipo: "mfp" },
  { id: "pa-m6700d", marcaId: "pantum", nombre: "M6700D", tipo: "mfp" },
  { id: "pa-m6700dw", marcaId: "pantum", nombre: "M6700DW", tipo: "mfp" },
  { id: "pa-m6800fdw", marcaId: "pantum", nombre: "M6800FDW", tipo: "mfp" },
  { id: "pa-m7100dn", marcaId: "pantum", nombre: "M7100DN", tipo: "mfp" },
  { id: "pa-m7100dw", marcaId: "pantum", nombre: "M7100DW", tipo: "mfp" },
  { id: "pa-m7200fdw", marcaId: "pantum", nombre: "M7200FDW", tipo: "mfp" },
  { id: "pa-cm1100adw", marcaId: "pantum", nombre: "CM1100ADW", tipo: "mfp" },
  { id: "pa-cm1100dw", marcaId: "pantum", nombre: "CM1100DW", tipo: "mfp" },
  { id: "pa-cp1100dw", marcaId: "pantum", nombre: "CP1100DW", tipo: "laser" },
  { id: "pa-cp2200dw", marcaId: "pantum", nombre: "CP2200DW", tipo: "laser" },
  { id: "pa-cp2500dw", marcaId: "pantum", nombre: "CP2500DW", tipo: "laser" },

  // ── OKI ──
  { id: "ok-b412dn", marcaId: "oki", nombre: "B412dn", tipo: "laser" },
  { id: "ok-b432dn", marcaId: "oki", nombre: "B432dn", tipo: "laser" },
  { id: "ok-b512dn", marcaId: "oki", nombre: "B512dn", tipo: "laser" },
  { id: "ok-b721dn", marcaId: "oki", nombre: "B721dn", tipo: "laser" },
  { id: "ok-b731dn", marcaId: "oki", nombre: "B731dn", tipo: "laser" },
  { id: "ok-b820dn", marcaId: "oki", nombre: "B820dn", tipo: "laser" },
  { id: "ok-c332dn", marcaId: "oki", nombre: "C332dn", tipo: "laser" },
  { id: "ok-c532dn", marcaId: "oki", nombre: "C532dn", tipo: "laser" },
  { id: "ok-c612dn", marcaId: "oki", nombre: "C612dn", tipo: "laser" },
  { id: "ok-c650dn", marcaId: "oki", nombre: "C650dn", tipo: "laser" },
  { id: "ok-c712dn", marcaId: "oki", nombre: "C712dn", tipo: "laser" },
  { id: "ok-c824dn", marcaId: "oki", nombre: "C824dn", tipo: "laser" },
  { id: "ok-c844dn", marcaId: "oki", nombre: "C844dn", tipo: "laser" },
  { id: "ok-mc363dn", marcaId: "oki", nombre: "MC363dn", tipo: "mfp" },
  { id: "ok-mc563dn", marcaId: "oki", nombre: "MC563dn", tipo: "mfp" },
  { id: "ok-mc573dn", marcaId: "oki", nombre: "MC573dn", tipo: "mfp" },
  { id: "ok-mc853dn", marcaId: "oki", nombre: "MC853dn", tipo: "mfp" },
  { id: "ok-mc873dn", marcaId: "oki", nombre: "MC873dn", tipo: "mfp" },
  { id: "ok-es5162dn", marcaId: "oki", nombre: "ES5162dn", tipo: "mfp" },
  { id: "ok-es5473dn", marcaId: "oki", nombre: "ES5473dn", tipo: "mfp" },
  { id: "ok-es8431dn", marcaId: "oki", nombre: "ES8431dn", tipo: "laser" },

  // ── Dell ──
  { id: "dl-e310dw", marcaId: "dell", nombre: "E310dw", tipo: "laser" },
  { id: "dl-e514dw", marcaId: "dell", nombre: "E514dw", tipo: "mfp" },
  { id: "dl-e515dw", marcaId: "dell", nombre: "E515dw", tipo: "mfp" },
  { id: "dl-e525w", marcaId: "dell", nombre: "E525w", tipo: "mfp" },
  { id: "dl-s2810dn", marcaId: "dell", nombre: "S2810dn", tipo: "laser" },
  { id: "dl-s2815dn", marcaId: "dell", nombre: "S2815dn", tipo: "mfp" },
  { id: "dl-s2825cdn", marcaId: "dell", nombre: "S2825cdn", tipo: "mfp" },
  { id: "dl-s2830dn", marcaId: "dell", nombre: "S2830dn", tipo: "laser" },
  { id: "dl-s2840dn", marcaId: "dell", nombre: "S2840dn", tipo: "laser" },
  { id: "dl-c2660dn", marcaId: "dell", nombre: "C2660dn", tipo: "laser" },
  { id: "dl-c2665dnf", marcaId: "dell", nombre: "C2665dnf", tipo: "mfp" },
  { id: "dl-c3760dn", marcaId: "dell", nombre: "C3760dn", tipo: "laser" },
  { id: "dl-c3765dnf", marcaId: "dell", nombre: "C3765dnf", tipo: "mfp" },
  { id: "dl-b2375dnf", marcaId: "dell", nombre: "B2375dnf", tipo: "mfp" },
  { id: "dl-b3460dn", marcaId: "dell", nombre: "B3460dn", tipo: "laser" },
  { id: "dl-b3465dnf", marcaId: "dell", nombre: "B3465dnf", tipo: "mfp" },
  { id: "dl-h625cdw", marcaId: "dell", nombre: "H625cdw", tipo: "mfp" },
  { id: "dl-h825cdw", marcaId: "dell", nombre: "H825cdw", tipo: "mfp" },
  { id: "dl-s2820dn", marcaId: "dell", nombre: "S2820dn", tipo: "laser" },

  // ── Samsung (legacy / Xpress / ProXpress) ──
  { id: "sm-m2020w", marcaId: "samsung", nombre: "Xpress M2020W", tipo: "laser" },
  { id: "sm-m2022w", marcaId: "samsung", nombre: "Xpress M2022W", tipo: "laser" },
  { id: "sm-m2835dw", marcaId: "samsung", nombre: "Xpress M2835DW", tipo: "laser" },
  { id: "sm-m2885fw", marcaId: "samsung", nombre: "Xpress M2885FW", tipo: "mfp" },
  { id: "sm-m3015dw", marcaId: "samsung", nombre: "ProXpress M3015DW", tipo: "laser" },
  { id: "sm-m3325nd", marcaId: "samsung", nombre: "ProXpress M3325ND", tipo: "laser" },
  { id: "sm-m3370fd", marcaId: "samsung", nombre: "ProXpress M3370FD", tipo: "mfp" },
  { id: "sm-m3820dw", marcaId: "samsung", nombre: "ProXpress M3820DW", tipo: "laser" },
  { id: "sm-m3870fw", marcaId: "samsung", nombre: "ProXpress M3870FW", tipo: "mfp" },
  { id: "sm-m4020nd", marcaId: "samsung", nombre: "ProXpress M4020ND", tipo: "laser" },
  { id: "sm-m4070fr", marcaId: "samsung", nombre: "ProXpress M4070FR", tipo: "mfp" },
  { id: "sm-m4530nd", marcaId: "samsung", nombre: "ProXpress M4530ND", tipo: "laser" },
  { id: "sm-m4580fx", marcaId: "samsung", nombre: "ProXpress M4580FX", tipo: "mfp" },
  { id: "sm-c410w", marcaId: "samsung", nombre: "Xpress C410W", tipo: "laser" },
  { id: "sm-c430w", marcaId: "samsung", nombre: "Xpress C430W", tipo: "laser" },
  { id: "sm-c480w", marcaId: "samsung", nombre: "Xpress C480W", tipo: "mfp" },
  { id: "sm-c480fw", marcaId: "samsung", nombre: "Xpress C480FW", tipo: "mfp" },
  { id: "sm-c1860fw", marcaId: "samsung", nombre: "Xpress C1860FW", tipo: "mfp" },
  { id: "sm-sl-m2020w", marcaId: "samsung", nombre: "SL-M2020W", tipo: "laser" },
  { id: "sm-sl-m2070w", marcaId: "samsung", nombre: "SL-M2070W", tipo: "mfp" },
  { id: "sm-sl-m2835dw", marcaId: "samsung", nombre: "SL-M2835DW", tipo: "laser" },
  { id: "sm-sl-c430w", marcaId: "samsung", nombre: "SL-C430W", tipo: "laser" },
  { id: "sm-sl-c480fw", marcaId: "samsung", nombre: "SL-C480FW", tipo: "mfp" },
];

export function getImpresoraMarcaById(
  marcaId: string,
): ImpresoraMarcaCatalogItem | undefined {
  return IMPRESORA_MARCAS_CATALOG.find((marca) => marca.id === marcaId);
}

export function listImpresoraModelosByMarca(
  marcaId: string,
): ImpresoraModeloCatalogItem[] {
  return IMPRESORA_MODELOS_CATALOG.filter((modelo) => modelo.marcaId === marcaId);
}

export function findImpresoraMarcaByNombre(
  nombre: string | null | undefined,
): ImpresoraMarcaCatalogItem | undefined {
  const needle = nombre?.trim().toLowerCase();
  if (!needle) return undefined;
  return IMPRESORA_MARCAS_CATALOG.find(
    (marca) => marca.nombre.toLowerCase() === needle,
  );
}

export function findImpresoraModeloByNombre(
  marcaId: string,
  nombre: string | null | undefined,
): ImpresoraModeloCatalogItem | undefined {
  const needle = nombre?.trim().toLowerCase();
  if (!needle || !marcaId) return undefined;
  return listImpresoraModelosByMarca(marcaId).find(
    (modelo) => modelo.nombre.toLowerCase() === needle,
  );
}
